name: shop_it
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #framework
  stacked: ^3.4.1+1
  stacked_services: ^1.3.0
  flex_color_scheme: ^7.3.1
  freezed_annotation: ^2.4.1
  freezed: ^2.4.5
  shared_preferences: ^2.2.2
  #ui
  animations: ^2.0.8
  fluttertoast: ^8.2.4
  extended_image: ^8.1.1
  flutter_svg: ^2.0.9
  carousel_slider: ^4.2.1
  #api
  retrofit: ^4.0.3

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.2
  stacked_generator: ^1.5.1
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - locale/